version: '3'

services:
  api:
    build: ./api
    ports:
      - "5080:5000"
    environment:
      FLASK_DEBUG: 1
      FLASK_APP: app
    volumes:
      - $PWD/api/app:/reform-api/app

  web:
    build: ./spa
    ports:
      - "3000:3000"
    environment:
      NODE_PATH: src/
      REACT_APP_ENV: dev
      REACT_APP_API_HOST: http://localhost:5080
    depends_on:
      - api